repos:
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.390  # Use the latest version
    hooks:
      - id: pyright
        name: pyright
        entry: .venv/bin/pyright
        language: system
        types: [ python ]
        pass_filenames: false